/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bsn.bsnOtros;
import clases.otros;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Alonso
 */
public class Inventario_otros extends javax.swing.JFrame {

    /**
     * Creates new form Inventario_otros
     */
    String Clave ="";
    bsnOtros bsn = new bsnOtros();
    
    public Inventario_otros() {
        initComponents();
        tbl_otros.setModel(bsn.ModeloBase());
        tbl_otros.setModel(bsn.datostabla());
        Habilitar(false);
        this.setLocationRelativeTo(null);
        btn_eliminar.setVisible(false);
        btn_modificar.setVisible(false);
        btn_aceptar.setVisible(false);
        btn_cancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titulo = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_otros = new javax.swing.JTable();
        btn_nuevo = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        count_cant = new javax.swing.JSpinner();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("Inventario");
        jPanel1.add(txt_titulo);
        txt_titulo.setBounds(30, 10, 180, 90);

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Screenshot_2.png"))); // NOI18N
        jPanel1.add(lbl_img);
        lbl_img.setBounds(220, 20, 330, 70);

        tbl_otros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_otros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_otrosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_otros);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 480, 260);

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevo);
        btn_nuevo.setBounds(640, 30, 130, 40);

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar);
        btn_eliminar.setBounds(540, 250, 80, 30);

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar);
        btn_modificar.setBounds(540, 200, 80, 30);

        jLabel1.setText("Equipo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 110, 80, 30);
        jPanel1.add(txt_nombre);
        txt_nombre.setBounds(640, 140, 150, 30);

        jLabel2.setText("Marca-Modelo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(640, 190, 90, 30);
        jPanel1.add(txt_marca);
        txt_marca.setBounds(640, 220, 150, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(630, 110, 20, 330);

        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 280, 80, 30);
        jPanel1.add(count_cant);
        count_cant.setBounds(700, 280, 60, 30);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_aceptar);
        btn_aceptar.setBounds(650, 410, 130, 30);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar);
        btn_cancelar.setBounds(670, 450, 90, 30);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 470, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        Habilitar(true);
        Limpiar();
        btn_modificar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_aceptar.setVisible(true);
        btn_cancelar.setVisible(true);
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
      btn_nuevo.setEnabled(false);
      Habilitar(true);
      btn_aceptar.setVisible(true);
      btn_cancelar.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        Habilitar(false);
        btn_eliminar.setEnabled(true);
        btn_modificar.setEnabled(true);
        btn_aceptar.setVisible(false);
        btn_cancelar.setVisible(false);
        Limpiar();
        btn_nuevo.setEnabled(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        String equipo = txt_nombre.getText().toUpperCase();
        String marca = txt_marca.getText();
        String xxx = "";
        Integer cant = Integer.parseInt(count_cant.getValue().toString());
        otros Otro = new otros(equipo, marca, xxx, cant);
        
        
        if (btn_nuevo.isEnabled()){
            bsn.Agregar(Otro);
            
        }else if(btn_modificar.isEnabled()){
            bsn.Modificar(Otro,Clave);
        }
        ActualizarTabla();
        Limpiar();
        Habilitar(false);
        btn_aceptar.setVisible(false);btn_cancelar.setVisible(false);btn_nuevo.setEnabled(true);
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void tbl_otrosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_otrosMouseReleased
        btn_eliminar.setVisible(true);
        btn_modificar.setVisible(true);
        Asignardatos(tbl_otros.getSelectedRow());
        Habilitar(false);
        btn_aceptar.setVisible(false);
       btn_cancelar.setVisible(false);
    }//GEN-LAST:event_tbl_otrosMouseReleased

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        String equipo = tbl_otros.getModel().getValueAt(tbl_otros.getSelectedRow(), 0).toString();
        String marca = tbl_otros.getModel().getValueAt(tbl_otros.getSelectedRow(), 1).toString();
        String xxx = "";
        Integer cant = Integer.parseInt(tbl_otros.getModel().getValueAt(tbl_otros.getSelectedRow(), 3).toString());
        otros Otro = new otros(equipo, marca, xxx, cant);
        if (JOptionPane.showConfirmDialog(null, "Desea eliminar "+equipo+" / "+marca) == JOptionPane.OK_OPTION){
            bsn.Eliminar(Otro);
            ActualizarTabla();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Opciones opc = new Opciones();
        opc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario_otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario_otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario_otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario_otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario_otros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JSpinner count_cant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTable tbl_otros;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables

    private void Habilitar(boolean b) {
       txt_marca.setEnabled(b);
       txt_nombre.setEnabled(b);
       count_cant.setEnabled(b);
    }

    private void Asignardatos(int selectedRow) {
         txt_marca.setText(tbl_otros.getModel().getValueAt(selectedRow, 1).toString());
         txt_nombre.setText(tbl_otros.getModel().getValueAt(selectedRow, 0).toString());
         count_cant.setValue(Integer.parseInt(tbl_otros.getModel().getValueAt(selectedRow, 3).toString()));
         Clave = txt_nombre.getText()+"%"+txt_marca.getText();
    }
    
    private void ActualizarTabla(){
        tbl_otros.removeAll();
        tbl_otros.setModel(bsn.datostabla());
    }

    private void Limpiar() {
        txt_marca.setText("");
       txt_nombre.setText("");
       count_cant.setValue(0);

    }
}
