/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bsn.bsnDron;
import clases.Dron;
import interfaz.Inventario;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;

/**
 *
 * @author Felipe Alonso
 */
public class nuevo_dron extends javax.swing.JDialog {

    bsnDron bsn = new bsnDron();
    Inventario inventario;

    public nuevo_dron(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        lbl_titulo.setText("NUEVO DRON:");
        this.setTitle("NUEVO DRON:");
        txt_fecha_estado.setText(AsignarFecha());
        Cargar_modeoSpinner();
    }

    public nuevo_dron(java.awt.Frame parent, boolean modal, String num_serie) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(0);
        this.setLocationRelativeTo(null);
        lbl_titulo.setText("MODIFICAR DRON");
        this.setTitle("MODIFICAR DRON");
        MostrarDatos(num_serie);
        JLabel lbl_estado_act = new JLabel();
        JTextField txt_estado_act = new JTextField();
        txt_fecha_estado.setText(AsignarFecha());
        Cargar_modeoSpinner();
        //lbl_estado_act.setAlignmentX(0);
    }

    private nuevo_dron(JFrame jFrame, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_tipo_equipo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_num_serie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_obs = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_otros = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cont_adap_bateria = new javax.swing.JSpinner();
        cont_helices = new javax.swing.JSpinner();
        cont_control = new javax.swing.JSpinner();
        cont_bateria = new javax.swing.JSpinner();
        cont_gimball = new javax.swing.JSpinner();
        cont_adaptador = new javax.swing.JSpinner();
        cont_maleta = new javax.swing.JSpinner();
        cont_protec_helices = new javax.swing.JSpinner();
        cont_helices_repuesto = new javax.swing.JSpinner();
        cont_cables_usb = new javax.swing.JSpinner();
        cont_cargador = new javax.swing.JSpinner();
        cont_enchufe = new javax.swing.JSpinner();
        txt_estado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        a = new javax.swing.JButton();
        txt_fecha_estado = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(842, 601));

        jPanel1.setMaximumSize(new java.awt.Dimension(842, 601));
        jPanel1.setMinimumSize(new java.awt.Dimension(842, 601));
        jPanel1.setPreferredSize(new java.awt.Dimension(842, 601));
        jPanel1.setLayout(null);

        lbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_titulo.setText("TITULO:");
        jPanel1.add(lbl_titulo);
        lbl_titulo.setBounds(29, 29, 380, 60);

        jLabel2.setText("Tipo Equipo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 110, 80, 40);

        jLabel3.setText("Marca-Modelo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 90, 30);

        jLabel4.setText("Nº de serie: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 220, 70, 40);

        jLabel5.setText("Cantidad: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 270, 70, 40);
        jPanel1.add(txt_cantidad);
        txt_cantidad.setBounds(120, 270, 50, 40);

        txt_tipo_equipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tipo_equipoKeyReleased(evt);
            }
        });
        jPanel1.add(txt_tipo_equipo);
        txt_tipo_equipo.setBounds(120, 110, 180, 40);
        jPanel1.add(txt_marca);
        txt_marca.setBounds(120, 160, 180, 40);
        jPanel1.add(txt_num_serie);
        txt_num_serie.setBounds(120, 220, 180, 40);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 540, 120, 40);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 540, 120, 40);

        jLabel6.setText("Helices:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 320, 80, 30);

        jLabel7.setText("Bateria:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 400, 80, 30);

        jLabel8.setText("Adaptador de baterias:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 440, 130, 30);

        jLabel9.setText("Protectores de Helice:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 210, 130, 30);

        jLabel10.setText("Control:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 360, 80, 30);

        jLabel11.setText("Adaptador:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(330, 110, 80, 30);

        jLabel12.setText("Maleta o Mochila:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(330, 160, 100, 30);

        jLabel13.setText("Gimball:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 440, 100, 30);

        jLabel14.setText("Helice Repuesto:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(330, 260, 100, 30);

        jLabel15.setText("Cables USB:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 310, 100, 30);

        jLabel16.setText("Enchufe de cargador: ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(330, 400, 130, 30);

        jLabel17.setText("Cagador de Baterias:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(330, 350, 130, 30);

        jLabel18.setText("Observaciones:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(560, 110, 110, 30);

        txt_obs.setColumns(20);
        txt_obs.setRows(5);
        txt_obs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_obsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txt_obs);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(560, 150, 230, 100);

        jLabel19.setText("Otros:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(560, 280, 110, 30);

        txt_otros.setColumns(20);
        txt_otros.setRows(5);
        jScrollPane2.setViewportView(txt_otros);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(560, 320, 230, 100);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(540, 110, 30, 390);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(310, 110, 30, 350);
        jPanel1.add(cont_adap_bateria);
        cont_adap_bateria.setBounds(450, 440, 50, 30);

        cont_helices.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cont_helicesPropertyChange(evt);
            }
        });
        cont_helices.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cont_helicesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cont_helicesKeyTyped(evt);
            }
        });
        jPanel1.add(cont_helices);
        cont_helices.setBounds(120, 320, 50, 30);
        jPanel1.add(cont_control);
        cont_control.setBounds(120, 360, 50, 30);
        jPanel1.add(cont_bateria);
        cont_bateria.setBounds(120, 400, 50, 30);
        jPanel1.add(cont_gimball);
        cont_gimball.setBounds(120, 440, 50, 30);
        jPanel1.add(cont_adaptador);
        cont_adaptador.setBounds(450, 110, 50, 30);
        jPanel1.add(cont_maleta);
        cont_maleta.setBounds(450, 160, 50, 30);
        jPanel1.add(cont_protec_helices);
        cont_protec_helices.setBounds(450, 210, 50, 30);
        jPanel1.add(cont_helices_repuesto);
        cont_helices_repuesto.setBounds(450, 260, 50, 30);
        jPanel1.add(cont_cables_usb);
        cont_cables_usb.setBounds(450, 300, 50, 30);
        jPanel1.add(cont_cargador);
        cont_cargador.setBounds(450, 350, 50, 30);
        jPanel1.add(cont_enchufe);
        cont_enchufe.setBounds(450, 400, 50, 30);

        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_estado);
        txt_estado.setBounds(630, 440, 160, 30);

        jLabel20.setText("Estado:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(560, 440, 60, 30);

        a.setText("Borrar Datos");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(600, 20, 160, 50);

        txt_fecha_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fecha_estadoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fecha_estado);
        txt_fecha_estado.setBounds(660, 480, 130, 30);

        jLabel21.setText("Fecha Estado:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(560, 480, 90, 30);
        jPanel1.add(lbl_fecha);
        lbl_fecha.setBounds(660, 520, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tipo_equipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tipo_equipoKeyReleased

    }//GEN-LAST:event_txt_tipo_equipoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String equipo = txt_tipo_equipo.getText();
        String marca = txt_marca.getText();
        String num_serie = txt_num_serie.getText();
        String obs = txt_obs.getText();
        String otros = txt_otros.getText();
        String estado = txt_estado.getText();
        String fecha_estado = txt_fecha_estado.getText();

        Integer cant = Integer.parseInt(txt_cantidad.getText());
        Integer adap_bat = Integer.parseInt(cont_adap_bateria.getValue().toString());
        Integer adap = Integer.parseInt(cont_adaptador.getValue().toString());
        Integer bateria = Integer.parseInt(cont_bateria.getValue().toString());
        Integer control = Integer.parseInt(cont_control.getValue().toString());
        Integer enchufe = Integer.parseInt(cont_enchufe.getValue().toString());
        Integer gimball = Integer.parseInt(cont_gimball.getValue().toString());
        Integer helices = Integer.parseInt(cont_helices.getValue().toString());
        Integer helices_r = Integer.parseInt(cont_helices_repuesto.getValue().toString());
        Integer maleta = Integer.parseInt(cont_maleta.getValue().toString());
        Integer prot_helices = Integer.parseInt(cont_protec_helices.getValue().toString());
        Integer usb = Integer.parseInt(cont_cables_usb.getValue().toString());
        Integer cargador = Integer.parseInt(cont_cargador.getValue().toString());

        if (num_serie.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese n° de serie del producto");
        } else if ( lbl_titulo.getText().equals("NUEVO DRON:")) {
            Dron dron = new Dron(equipo, marca, num_serie, cant, helices, gimball, bateria, control, adap, maleta, prot_helices, helices_r, usb, cargador, enchufe, adap_bat, obs, otros, estado,fecha_estado);
            bsn.Agregar(dron);

            if (JOptionPane.showConfirmDialog(this, "Agregar otro Producto?") == JOptionPane.OK_OPTION) {
                Limpiar();
            } else {
                this.dispose();
                inventario = new Inventario();
                inventario.setVisible(true);
            }
        }else{
           Dron dron = new Dron(equipo, marca, num_serie, cant, helices, gimball, bateria, control, adap, maleta, prot_helices, helices_r, usb, cargador, enchufe, adap_bat, obs, otros, estado, fecha_estado);
           bsn.Actualizar(dron);
           this.dispose();
           inventario = new Inventario();
           inventario.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        inventario = new Inventario();

        inventario.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        Limpiar();
    }//GEN-LAST:event_aActionPerformed

    private void cont_helicesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cont_helicesPropertyChange
            
    }//GEN-LAST:event_cont_helicesPropertyChange

    private void txt_fecha_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fecha_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fecha_estadoActionPerformed

    private void cont_helicesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cont_helicesKeyTyped

    }//GEN-LAST:event_cont_helicesKeyTyped

    private void cont_helicesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cont_helicesKeyReleased

    }//GEN-LAST:event_cont_helicesKeyReleased

    private void txt_obsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_obsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_obsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevo_dron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevo_dron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevo_dron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevo_dron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nuevo_dron dialog = new nuevo_dron(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JSpinner cont_adap_bateria;
    private javax.swing.JSpinner cont_adaptador;
    private javax.swing.JSpinner cont_bateria;
    private javax.swing.JSpinner cont_cables_usb;
    private javax.swing.JSpinner cont_cargador;
    private javax.swing.JSpinner cont_control;
    private javax.swing.JSpinner cont_enchufe;
    private javax.swing.JSpinner cont_gimball;
    private javax.swing.JSpinner cont_helices;
    private javax.swing.JSpinner cont_helices_repuesto;
    private javax.swing.JSpinner cont_maleta;
    private javax.swing.JSpinner cont_protec_helices;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_fecha_estado;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_num_serie;
    private javax.swing.JTextArea txt_obs;
    private javax.swing.JTextArea txt_otros;
    private javax.swing.JTextField txt_tipo_equipo;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txt_cantidad.setText("");
        txt_marca.setText("");
        txt_num_serie.setText("");
        txt_tipo_equipo.setText("");
        txt_obs.setText("");
        txt_otros.setText("");
        txt_estado.setText("");

        cont_adap_bateria.setValue(0);
        cont_adaptador.setValue(0);
        cont_bateria.setValue(0);
        cont_cables_usb.setValue(0);
        cont_cargador.setValue(0);
        cont_control.setValue(0);
        cont_enchufe.setValue(0);
        cont_gimball.setValue(0);
        cont_helices.setValue(0);
        cont_helices_repuesto.setValue(0);
        cont_maleta.setValue(0);
        cont_protec_helices.setValue(0);

    }

    private void MostrarDatos(String num_serie) {
        Dron dron = new Dron(bsn.CargarDatos(num_serie));

        txt_tipo_equipo.setText(dron.getEquipo());
        txt_marca.setText(dron.getMarca());
        txt_num_serie.setText(dron.getNum_serie());
        txt_cantidad.setText(dron.getCant().toString());
        cont_helices.setValue(dron.getHelice());
        cont_control.setValue(dron.getControl());
        cont_bateria.setValue(dron.getBateria());
        cont_protec_helices.setValue(dron.getProtector_helice());
        cont_adaptador.setValue(dron.getAdaptador());
        cont_maleta.setValue(dron.getMochila());
        cont_gimball.setValue(dron.getGimball());
        cont_helices_repuesto.setValue(dron.getHelice_repuesto());
        cont_cables_usb.setValue(dron.getCable_usb());
        cont_cargador.setValue(dron.getCargador());
        cont_enchufe.setValue(dron.getEnchufe_cargador());
        txt_otros.setText(dron.getOtros());
        txt_obs.setText(dron.getObs());
        cont_adap_bateria.setValue(dron.getAdaptador_bateria());
        txt_estado.setText(dron.getEstado());
        txt_fecha_estado.setText(AsignarFecha());
        lbl_fecha.setText(dron.getFecha_estado());
        //dron.getEstado_actual();

    }

    private String AsignarFecha() {
      Calendar calendario = Calendar.getInstance();
      int mes = calendario.get(Calendar.MONTH) +1;
      String fecha = calendario.get(Calendar.DATE) +"/"+
                     mes +"/"+
                    calendario.get(Calendar.YEAR);
      return fecha;
    }

    
    private SpinnerModel modeloSpinner(){
        // base, min, max, step
        SpinnerModel modelo = new SpinnerNumberModel(0, 0, 99, 1);
        return modelo;
    }
    
    private void Cargar_modeoSpinner(){
        cont_adap_bateria.setModel(modeloSpinner());
        cont_adaptador.setModel(modeloSpinner());
        cont_bateria.setModel(modeloSpinner());
        cont_cables_usb.setModel(modeloSpinner());
        cont_cargador.setModel(modeloSpinner());
        cont_control.setModel(modeloSpinner());
        cont_enchufe.setModel(modeloSpinner());
        cont_gimball.setModel(modeloSpinner());
        cont_helices.setModel(modeloSpinner());
        cont_helices_repuesto.setModel(modeloSpinner());
        cont_maleta.setModel(modeloSpinner());
        cont_protec_helices.setModel(modeloSpinner());
    }
}
