/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bsn.bsnDron;
import bsn.bsnOtros;
import codigobarras.GenerarPDF;
import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Alonso
 */
public class Opciones extends javax.swing.JFrame {

    Inventario inventario;
    Inventario_otros otros;
    bsnDron bsnD = new bsnDron();
    bsnOtros bsnO = new bsnOtros();
    String ruta;

    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        ruta = System.getProperty("user.home") + "\\Codigos.pdf";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(521, 257));

        jPanel1.setMaximumSize(new java.awt.Dimension(521, 257));
        jPanel1.setMinimumSize(new java.awt.Dimension(521, 257));
        jPanel1.setPreferredSize(new java.awt.Dimension(521, 257));
        jPanel1.setLayout(null);

        jButton1.setText("Drones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 150, 160, 60);

        jButton2.setText("Otros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 150, 150, 60);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 180, 60);

        jButton3.setText("Generar códigos de barra");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 240, 190, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        inventario = new Inventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        otros = new Inventario_otros();
        otros.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String mensaje = "Marque Productos:";
        JCheckBox[] chk = Check();
        Object[] msg = {mensaje, chk};

        if (JOptionPane.showConfirmDialog(null, msg) == JOptionPane.OK_OPTION) {
            GenerarPDF(chk);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Desea abrir archivo generado?") == JOptionPane.OK_OPTION) {
            try {
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + ruta);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JCheckBox[] Check() {
        String nombreD[] = new String[bsnD.CantidadNombres()];
        String nombreO[] = new String[bsnO.CantidadNombres()];
        JCheckBox chkBox[] = new JCheckBox[bsnD.CantidadNombres() + bsnO.CantidadNombres()];
        int i = 0;
        int j = 0;

        nombreD = bsnD.ObtenerNombres();
        nombreO = bsnO.ObtenerNombres();

        while (i < bsnD.CantidadNombres()) {
            chkBox[i] = new JCheckBox(nombreD[i]);
            add(chkBox[i]);
            i++;
        }

        while (j < bsnO.CantidadNombres()) {
            chkBox[i] = new JCheckBox(nombreD[j]);
            add(chkBox[i]);
            j++;
            i++;
        }

        return chkBox;

    }

    private void GenerarPDF(JCheckBox[] chk) {
        GenerarPDF pdf = new GenerarPDF();
        pdf.GenerarPDF("Codigos de Barra", ruta, chk);
    }
}
