/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import bsn.bsnDron;
import bsn.bsnOtros;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument.Content;

/**
 *
 * @author Felipe Alonso
 */
public class Opciones extends javax.swing.JFrame {

    Inventario inventario;
    Inventario_otros otros;
    bsnDron bsnD = new bsnDron();
    bsnOtros bsnO = new bsnOtros();
    
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_gencod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(575, 349));
        setMinimumSize(new java.awt.Dimension(575, 349));

        jPanel1.setMaximumSize(new java.awt.Dimension(575, 349));
        jPanel1.setMinimumSize(new java.awt.Dimension(575, 349));
        jPanel1.setPreferredSize(new java.awt.Dimension(575, 349));
        jPanel1.setLayout(null);

        jButton1.setText("Drones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 120, 160, 60);

        jButton2.setText("Otros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 120, 150, 60);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 180, 60);

        btn_gencod.setText("Generar Codigo de Barra");
        btn_gencod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gencodActionPerformed(evt);
            }
        });
        jPanel1.add(btn_gencod);
        btn_gencod.setBounds(190, 230, 160, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        inventario = new Inventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
       otros = new Inventario_otros();
       otros.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_gencodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gencodActionPerformed
       String mensaje = "";
       Object[] msg = {mensaje,Check()};
       
       JOptionPane.showConfirmDialog(null, msg);
    }//GEN-LAST:event_btn_gencodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gencod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private JCheckBox[] Check() {
        String NombreD[] = new String[bsnD.CantidadNombres()];
        String NombreO[] = new String[bsnO.CantidadNombres()];
        JCheckBox checkBox[] = new JCheckBox[bsnD.CantidadNombres()+bsnO.CantidadNombres()];
        
        NombreD = bsnD.ObtenerNombres();
        NombreO = bsnO.ObtenerNombres();
        int i=0;int j=0;
        
        while (i<bsnD.CantidadNombres()) {
               checkBox[i] = new JCheckBox(NombreD[i]);add(checkBox[i]);
               i++;
        }
        
        while (j<bsnO.CantidadNombres()) {
               checkBox[i] = new JCheckBox(NombreD[j]);add(checkBox[i]);
               i++;j++;
        }
        
        return checkBox;
    }
}
